### ISSUE TITLE
No definition found for class:'androidx.work.WorkerParameters'

### ISSUE THREAD

**Issue by tyczj** [InsertKoinIO/koin#1623]
**Describe the bug**
Using 3.4.2 of koin work manager I am getting this error sometimes when trying to start a work manager instance

```
* Instance creation error : could not create instance for '[Factory:'x.x.x.x.workers.DailyMaintenanceWorker',qualifier:q:'x.x.x.x.workers.DailyMaintenanceWorker',binds:androidx.work.ListenableWorker]': org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters' q:''. Check your definitions!
  org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
  org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
  org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  org.koin.core.scope.Scope.get(Scope.kt:210)
  x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:221)
  x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:94)
  org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
  org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
  org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
  org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
  org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  org.koin.core.scope.Scope.get(Scope.kt:210)
  org.koin.core.scope.Scope.getOrNull(Scope.kt:175)
  org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
  androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
  androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
  androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
  androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
  androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.lang.Thread.run(Thread.java:923)
E  Unable to instantiate a ListenableWorker (x.x.x.x.workers.DailyMaintenanceWorker)
  org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'x.x.x.x.workers.DailyMaintenanceWorker',qualifier:q:'x.x.x.x.workers.DailyMaintenanceWorker',binds:androidx.work.ListenableWorker]'
  at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
  at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  at org.koin.core.scope.Scope.get(Scope.kt:210)
  at org.koin.core.scope.Scope.getOrNull(Scope.kt:175)
  at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
  at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
  at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
  at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
  at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
  at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923)
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters' q:''. Check your definitions!
  at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  at org.koin.core.scope.Scope.get(Scope.kt:210)
  at x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:221)
  at x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:94)
  at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
  at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116) 
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:246) 
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231) 
  at org.koin.core.scope.Scope.get(Scope.kt:210) 
  at org.koin.core.scope.Scope.getOrNull(Scope.kt:175) 
  at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47) 
  at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71) 
  at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83) 
  at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243) 
  at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145) 
  at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
  at java.lang.Thread.run(Thread.java:923) 
E  FATAL EXCEPTION: WM.task-3
  Process: x.x.x.x, PID: 1500
  java.lang.Error: org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'x.x.x.x.workers.DailyMaintenanceWorker',qualifier:q:'x.x.x.x.workers.DailyMaintenanceWorker',binds:androidx.work.ListenableWorker]'
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'x.x.x.x.workers.DailyMaintenanceWorker',qualifier:q:'x.x.x.x.workers.DailyMaintenanceWorker',binds:androidx.work.ListenableWorker]'
  at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
  at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  at org.koin.core.scope.Scope.get(Scope.kt:210)
  at org.koin.core.scope.Scope.getOrNull(Scope.kt:175)
  at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
  at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
  at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
  at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
  at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
  at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
  at java.lang.Thread.run(Thread.java:923) 
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters' q:''. Check your definitions!
  at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
  at org.koin.core.scope.Scope.get(Scope.kt:210)
  at x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:221)
  at x.x.x.x.AppBase$baseModule$1$invoke$$inlined$workerOf$default$7.invoke(WorkerOf.kt:94)
  at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
  at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
  at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116) 
  at org.koin.core.scope.Scope.resolveValue(Scope.kt:246) 
  at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231) 
  at org.koin.core.scope.Scope.get(Scope.kt:210) 
  at org.koin.core.scope.Scope.getOrNull(Scope.kt:175) 
  at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47) 
  at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71) 
  at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83) 
  at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243) 
  at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145) 
  at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
  at java.lang.Thread.run(Thread.java:923) 
```

The definition of work manager in my application class is just this

    workerOf(::DailyMaintenanceWorker)

This happens on a TCL Google TV device, Model# 32S356

I also have another Google TV from Sony and does not seem to happen though so it might be device dependent?

Can provide more information if needed

**To Reproduce**
Create a worker
Try to start worker upon app startup

**Expected behavior**
Worker launches without error

**Koin project used and used version (please complete the following information):**
 koin work manager 3.4.2
 koin core 3.4.2

**Additional moduleDefinition**

Work manager version 2.8.1

**Comment by tyczj** [comment]
in koin version 3.4.0 it still cannot create the worker but it does not fully crash the app like it does in 3.4.2.

 I get this error

```
E  Could not instantiate x.x.x.x.workers.IntervalWorker
java.lang.NoSuchMethodException: x.x.x.x.workers.IntervalWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
at java.lang.Class.getConstructor0(Class.java:2332)
at java.lang.Class.getDeclaredConstructor(Class.java:2170)
at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
E  Could not create Worker x.x.x.x.workers.IntervalWorker                    java.lang.NoSuchMethodException: x.x.x.x.workers.IntervalWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
at java.lang.Class.getConstructor0(Class.java:2332)
at java.lang.Class.getDeclaredConstructor(Class.java:2170)
at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by tyczj** [comment]
Looks like it's something similar to this [issue ](https://github.com/InsertKoinIO/koin/issues/1554) because as one of the comments states, if I do

`workerOf(::DailyMaintenanceWorker) { named<DailyMaintenanceWorker>() }`

everything seems to work fine again

**Comment by Nek-12** [comment]
That issue was not fully fixed. I have the same issue - it occurs rarely, which leads me to believe there is a race there.

**Comment by lucianocn** [comment]
I can confirm that the issue persists with Koin Work Manager 3.4.3 and Core 3.4.3 using `workerOf`.

**Comment by tyczj** [comment]
Even with 

`worker(named<DailyMaintenanceWorker>()) { DailyMaintenanceWorker(get())}`

it still happens so not limited to workerOf

**Comment by arnaudgiuliani** [comment]
anyone can help reproduce?

**Comment by arnaudgiuliani** [comment]
the othe thing to test, is to not use constructor injection but `by inject` to bypass the constructor injection of workerOf. Just to be sure, we know from where it comes.

**Comment by tyczj** [comment]
does that mean I need use `KoinComponent` on the work manager to be able to use `by inject`?

**Comment by arnaudgiuliani** [comment]
yes, to check the current context

**Comment by lucianocn** [comment]
Hi @arnaudgiuliani, here is the code that I use, which is causing the problem.

I have been unable to replicate this error in debug mode. It seems to manifest exclusively on production devices and occurs very rarely. Our app has approximately 200 devices utilizing it daily and the error arises ~3 times.

The occurrence seems to have begun after the modification of 'single' and 'worker' to 'singleOf' and 'workerOf'.

RepositoriesModule.kt
```
val repositoriesModule = module {
    singleOf(::SyncRepository) // 14 injections.
}
```

WorkersModule.kt
```
val workersModule = module {
    workerOf(::SyncWorker)
}
```

MyApplication.kt
```kotlin
class MyApplication : Application(), KoinComponent {

    override fun onCreate() {
        super.onCreate()

        // Koin
        startKoin {
            androidContext(this@MyApplication)
            workManagerFactory()
            modules(appModule) // Injects RepositoriesModule and WorkersModule
        }

        // SyncWorker - Periodic (15 minutes)
        syncWorkerPeriodic()
    }


    private fun syncWorkerPeriodic() {
        val constraintsBuilder: Constraints.Builder = Constraints.Builder()
            .setRequiredNetworkType(NetworkType.CONNECTED)

        val periodicWorkRequest = PeriodicWorkRequestBuilder<SyncWorker>(15, TimeUnit.MINUTES)
            .setConstraints(constraintsBuilder.build())
            .build()

        WorkManager.getInstance(applicationContext)
            .enqueueUniquePeriodicWork("syncWorkerPeriodic", ExistingPeriodicWorkPolicy.KEEP, periodicWorkRequest)
    }
}
```

SyncWorker.kt
```kotlin
class SyncWorker(
    context: Context,
    params: WorkerParameters,
    private val syncRepository: SyncRepository
) : CoroutineWorker(context, params), KoinComponent {
    @OptIn(SyncRepository.SyncDelicateMethod::class)
    override suspend fun doWork(): Result {
        val showFeedback = inputData.getBoolean("showFeedback", false)
        syncRepository.execWorker(showFeedback)
        return Result.success()
    }
}
```

------------

```
Error
org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.app.android.modules.core.workers.SyncWorker',qualifier:q:'com.app.android.modules.core.workers.SyncWorker',binds:androidx.work.ListenableWorker]'

InstanceCreationException
Could not create instance for '[Factory:'com.app.android.modules.core.workers.SyncWorker',qualifier:q:'com.app.android.modules.core.workers.SyncWorker',binds:androidx.work.ListenableWorker]'
```

**Comment by Mardaneus86** [comment]
Issue occurs here as well, but not reproducible in debug since it occurs very rarely. This will only be noticeable when the install-base is high enough. Currently about 13 users of the 2900 seem to be affected (about 0,5%).

We need to inject some custom dependencies in the worker, and don't want to add a Koin dependency in the Workers themselves because we want to keep the Workers DI-agnostic. That's why we're using the following format for initialisation in the Koin module, as an example:

```kotlin
worker(named<BackgroundWorker>()) {
    BackgroundWorker(
        context = androidContext(),
        params = get(),
        repository = get(),
        dispatcher = get(named(IO_DISPATCHER))
    )
}
```

I'm guessing @lucianocn's approach with the `workerOf(...) { named<...>() }` is not usable in that case?

**Comment by tyczj** [comment]
I let it run over the weekend with without using constructor injection and `KoinComponent`; didnt have any issues and it would have most likely have happened during that time.

Does that also mean I could remove all usages of `workerOf` when using KoinComponent?

**Comment by lucianocn** [comment]
The following code didn't resolve the problem 😵‍💫 

```
val workersModule = module {
    workerOf(::SyncWorker) { named<SyncWorker>() }
}
```

**Comment by Brock-Gibson** [comment]
@Mardaneus86 Facing the same problem at the moment. For your use of `KoinComponent`, were you using the default worker factory and injecting everything in the class itself or using a `DelegatingWorkerFactory` and injecting the dependencies into the class constructors there?

**Comment by lucianocn** [comment]
@Brock-Gibson
1) Remove `koin-androidx-workmanager` dependency and revert implementations (https://insert-koin.io/docs/reference/koin-android/workmanager/).
2) Add `androidx.work:work-runtime-ktx` dependency.
3) Implement worker with `KoinComponent` and `by inject`, like:

```kotlin
class SyncWorker(context: Context,params: WorkerParameters) : CoroutineWorker(context, params), KoinComponent {

    private val syncRepository: SyncRepository by inject() // <--

    override suspend fun doWork(): Result {
        val showFeedback = inputData.getBoolean("showFeedback", false)
        syncRepository.execWorker(showFeedback)
        return Result.success()
    }
}
```

**Comment by gerbiljames** [comment]
This is being caused by parameter resolution not being threadsafe, and is fixed by this [PR](https://github.com/InsertKoinIO/koin/pull/1561).  It's more likely to happen when multiple workers are triggered at the same time, which is often the case on production devices when `JobScheduler` wakes up apps to do batched work.

It doesn't happen when using `KoinComponent` since that doesn't use Koin to construct the worker, which means it never has to resolve the `WorkerParameters`.

**Comment by gerbiljames** [comment]
> do you think it's the case of parameter resolution for each worker? kindof race condition/thread safety problem.

I do, WorkManager manages a thread pool on which it creates workers, when enough workers are created at the same time there's a small chance that some are created on different threads in this pool which *may* trigger this bug.

**Comment by arnaudgiuliani** [comment]
closing this, let's reopen after 3.5.0 version update if needed 👍

**Comment by mak1nt0sh** [comment]
Still experiencing on Koin-4.0.0-RC1

**Comment by ChrisKruegerDev** [comment]
The issue still exists with the koin 4.0.0 and koin annotation 1.4.0-RC4

**Comment by dant3** [comment]
I can still see this issue in Koin 4.1.1

**Comment by arnaudgiuliani** [comment]
anyone to help make a reproducer? if someone has some code to help replay it?

**Comment by ChrisKruegerDev** [comment]
I haven't seen the issue anymore
